Feature user details screen
MoonLoone/roomer pull request #127
Opened 2023-04-28 15:48 UTC by Ret14

Реализовал экран деталей пользователя. Открывается при нажатии на карточку пользователя. С экрана еще нельзя смотреть кол-во отзывовов и переходить на экран создания отзыва, начинать переписку с пользователем. Добавил недостающие поля в класс User

2023-04-29 07:03 UTC, MoonLoone requested changes
Есть пара замечаний

2023-04-29 07:03 UTC, MoonLoone commented on app/src/main/res/values/strings.xml
> +    <string name="recommended_notification_title">Roomer</string>
Название приложения лучше пометить translatable = false

2023-04-29 07:03 UTC, MoonLoone commented on app/src/main/res/values/strings.xml
> +    <string name="searching_for_work">Searching \nFor Work</string>
Обязательно так делать?

2023-04-29 07:03 UTC, MoonLoone commented on app/src/main/res/values/strings.xml
> +    <string name="details_headline_user" translatable="false">%1$s %2$s, %3$d, %4$s</string>
Зачем это выносить в ресурсы?

2023-04-29 07:03 UTC, MoonLoone commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
Почему понизил версию грэдла?

2023-04-29 07:03 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/utils/navigation/UserTypeSerializer.kt
> +}
Где используется этот сериалайзер?

2023-04-29 07:16 UTC, Ret14 commented on app/src/main/java/com/example/roomer/domain/model/entities/User.kt
>  )
Serialized name необходим только если название переменной отличается от названия поля в json. Убрал там где не нужно. Лучше проставлять для всех полей?

2023-04-29 07:17 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/entrance/signup/about_me_avatar_screen/AboutMeAvatarScreen.kt
> +import com.example.roomer.utils.navigation.SignUpNavGraph
Понял, просто когда файл один проблем нет, но когда больше становится, уже хочется их в отдельную папку добавить

2023-04-29 07:18 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/navbar_screens/messenger_screen/MessengerScreenState.kt
> +package com.example.roomer.presentation.screens.navbar_screens.messenger_screen
Да, понял, буду с этим осторожнее

2023-04-29 07:24 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/UserDetailsScreen.kt
> +}
Думал. Гляну твои экраны, может придут идеи как разбить

2023-04-29 07:25 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/UserDetailsScreen.kt
> +//            Text(text = user.aboutMe ?: "", style = textStyleSecondary)
Сделал)

2023-04-29 07:27 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/UserDetailsScreen.kt
> +}
Да, но после добавления navigator нет смысла в этом коде, уберу

2023-04-29 07:31 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +            androidx.compose.material.Text(
Такое было с первой версии, это компонент Text из material, для него проставлены дефолтные стили material, вообще надо с обычным Text попробовать

2023-04-29 07:33 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/UserDetailsScreen.kt
> +}
У тебя тут верстки побольше, чем у меня) В целом можно разбить по блокам (как ты с названиями экранов регистрации сделал).

2023-04-29 07:36 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +const val DEFAULT_MINIMUM_TEXT_LINE = 3
Да, перенес в файл констант

2023-04-29 07:36 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +            Log.d("TABLE_LIST", it.toString())
Убрал

2023-04-29 07:38 UTC, Ret14 commented on app/src/main/res/values/strings.xml
> +    <string name="recommended_notification_title">Roomer</string>
Имеешь в виду все строки, в которых есть название приложения?

2023-04-29 07:38 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                            .dropLastWhile { Character.isWhitespace(it) || it == '.' }
Хорошо, сделаю

2023-04-29 07:40 UTC, Ret14 commented on app/src/main/res/values/strings.xml
> +    <string name="searching_for_work">Searching \nFor Work</string>
Нет, это быстро решало проблему, но лучше найти нужные размеры dp для элементов чтоб строка разбивалась сама по себе

2023-04-29 07:41 UTC, Ret14 commented on app/src/main/res/values/strings.xml
> +    <string name="details_headline_user" translatable="false">%1$s %2$s, %3$d, %4$s</string>
Мне показалось хорошей идеей. Это заголовок в деталях пользователя, он всегда будет в таком формате. Считаю это лучше чем в компоненте склеивать строки с пробелами

2023-04-29 07:43 UTC, Ret14 commented on app/src/main/java/com/example/roomer/utils/navigation/UserTypeSerializer.kt
> +}
Сериалайзер используется для передачи объекта пользователя на экран деталей

2023-04-29 07:46 UTC, Ret14 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
Студия так решила) Может оставим, зачем версия выше? Все отлично билдится. Или лучше мне 8 поставить?

2023-04-29 07:49 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/domain/model/entities/User.kt
>  )
Давай все же проставим для всех. Так повысится надежность, что ничего не сломается, когда кто-то решит переименовать поле)

2023-04-29 07:51 UTC, MoonLoone commented on app/src/main/res/values/strings.xml
> +    <string name="recommended_notification_title">Roomer</string>
Конкретно эту строчку. Название мы переводить не будем. messenger_notification_title при этом придется все же переводить

2023-04-29 07:52 UTC, MoonLoone commented on app/src/main/res/values/strings.xml
> +    <string name="searching_for_work">Searching \nFor Work</string>
Лучше так все же не делать. Мы в некоторых местах переиспользуем строки, могут возникнуть конфликты

2023-04-29 07:55 UTC, MoonLoone commented on app/src/main/res/values/strings.xml
> +    <string name="details_headline_user" translatable="false">%1$s %2$s, %3$d, %4$s</string>
Тогда мб стоит вынести в константы что-то вроде StringFormat? В strings все же обычно хранят то, что планируют переводить.

2023-04-29 07:55 UTC, MoonLoone commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
У меня тоже с этой версией все ок. Но у Вероники были проблемы

2023-04-29 07:56 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/utils/navigation/UserTypeSerializer.kt
> +}
Хорошо, не увидел)

2023-04-29 11:08 UTC, Iascatt commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
Не, с 7.5 все нормально., выбирайте на ваше усмотрение. Просто думала, что чем выше, тем лучше. Сколько времени пройдет до того, как и 7.5 устареет? Проблем с 8 не было вроде.

2023-04-29 12:18 UTC, Ret14 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
да, ок, я вернул 8

2023-04-30 09:14 UTC, MoonLoone approved these changes
Мелкие правки. В целом все хорошо

2023-04-30 09:14 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/UserDetailsScreen.kt
> +}
Сделай тут функции приватными.

2023-04-30 09:14 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/utils/UtilsFunctions.kt
> +}
Супер

2023-04-30 09:14 UTC, MoonLoone commented on app/src/main/res/values/strings.xml
> +    <string name="recommended_notification_title">Roomer</string>
Не поправил

2023-04-30 10:00 UTC, merged