Fix chat
MoonLoone/roomer pull request #141
Opened 2023-05-04 13:56 UTC by MoonLoone

Поработал с RemoteMediator, починил чат. Теперь корректно работает чат и избранное

2023-05-04 19:20 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                .padding(start = 16.dp)
хардкод

2023-05-04 19:22 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                        16
Кажется лучше константу сделать в этом элементе для максимальной длины строки

2023-05-04 19:30 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                            .width(48.dp)
хардкод

2023-05-04 19:31 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                .padding(top = 16.dp)
хардкод

2023-05-04 19:35 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
Убирай хардкод

2023-05-04 19:41 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                .padding(start = 16.dp)
хардкод

2023-05-04 19:41 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                    modifier = Modifier.padding(start = 8.dp),
хардкод

2023-05-04 19:41 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                .widthIn(min = 32.dp, max = 240.dp)
хардкод

2023-05-04 19:42 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                .padding(16.dp),
хардкод

2023-05-04 19:42 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                .padding(start = 40.dp, top = 16.dp)
хардкод

2023-05-04 19:42 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +                .widthIn(min = 32.dp, max = 240.dp)
хардкод

2023-05-04 19:42 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +            horizontalArrangement = Arrangement.spacedBy(32.dp),
хардкод

2023-05-04 19:50 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreenViewModel.kt
> +            val response = roomerRepository.getMessages(chatId = chatId)
может это из useCase делать?

2023-05-04 19:51 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreenViewModel.kt
> +        viewModelScope.launch {
Зачем корутина в корутине? Почему сразу в IO нельзя запустить?

2023-05-04 20:02 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreenViewModel.kt
> +            CoroutineScope(Dispatchers.IO).launch {
Снова корутина в корутине. Есть какие-то причины чтобы это невозможно было сделать в одной корутине?

2023-05-04 20:03 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreenViewModel.kt
> +                val token = SpManager().getSharedPreference(
каждый раз при вызове функции будет одинаковый токен приходить, может получать его один раз в init?

2023-05-04 20:08 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreenState.kt
> +    val noMessages: Boolean = false,
———————————No messages?———————————
⠀⣞⢽⢪⢣⢣⢣⢫⡺⡵⣝⡮⣗⢷⢽⢽⢽⣮⡷⡽⣜⣜⢮⢺⣜⢷⢽⢝⡽⣝
⠸⡸⠜⠕⠕⠁⢁⢇⢏⢽⢺⣪⡳⡝⣎⣏⢯⢞⡿⣟⣷⣳⢯⡷⣽⢽⢯⣳⣫⠇
⠀⠀⢀⢀⢄⢬⢪⡪⡎⣆⡈⠚⠜⠕⠇⠗⠝⢕⢯⢫⣞⣯⣿⣻⡽⣏⢗⣗⠏⠀
⠀⠪⡪⡪⣪⢪⢺⢸⢢⢓⢆⢤⢀⠀⠀⠀⠀⠈⢊⢞⡾⣿⡯⣏⢮⠷⠁⠀⠀
⠀⠀⠀⠈⠊⠆⡃⠕⢕⢇⢇⢇⢇⢇⢏⢎⢎⢆⢄⠀⢑⣽⣿⢝⠲⠉⠀⠀⠀⠀
⠀⠀⠀⠀⠀⡿⠂⠠⠀⡇⢇⠕⢈⣀⠀⠁⠡⠣⡣⡫⣂⣿⠯⢪⠰⠂⠀⠀⠀⠀
⠀⠀⠀⠀⡦⡙⡂⢀⢤⢣⠣⡈⣾⡃⠠⠄⠀⡄⢱⣌⣶⢏⢊⠂⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢝⡲⣜⡮⡏⢎⢌⢂⠙⠢⠐⢀⢘⢵⣽⣿⡿⠁⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠨⣺⡺⡕⡕⡱⡑⡆⡕⡅⡕⡜⡼⢽⡻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣼⣳⣫⣾⣵⣗⡵⡱⡡⢣⢑⢕⢜⢕⡝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣴⣿⣾⣿⣿⣿⡿⡽⡑⢌⠪⡢⡣⣣⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡟⡾⣿⢿⢿⢵⣽⣾⣼⣘⢸⢸⣞⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠁⠇⠡⠩⡫⢿⣝⡻⡮⣒⢽⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
—————————————————————————————

2023-05-04 20:09 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreen.kt
> +@Composable
Ого composable viewModel?

2023-05-04 20:20 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreen.kt
> +                                    editMessageText.value = TextFieldValue("")
TextFieldValue выглядит как костыль, почему бы просто строки не использовать?

2023-05-04 20:21 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreen.kt
> +                .padding(start = 8.dp)
хардкод

2023-05-04 20:22 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreen.kt
> +    navigateToUser: () -> Unit
Загадочно. Два параметра одного типа и почти одинаково называются. Добавь семантики)

2023-05-04 20:22 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreen.kt
> +                .padding(bottom = 8.dp),
хардкод

2023-05-04 20:23 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreen.kt
> +                16
хардкод

2023-05-04 20:24 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreen.kt
Уничтожь хардкод)

2023-05-04 20:26 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/navbar_screens/messenger_screen/MessengerScreen.kt
> +                    navigator.navigate(ChatScreenDestination(User(302)))
Тут ты кажется тестировал, убери это либо закомментируй если еще понадобится

2023-05-04 20:28 UTC, Ret14 commented on app/src/main/java/com/example/roomer/domain/usecase/navbar_screens/MessengerUseCase.kt
>                  emit(Resource.Error.GeneralError(message = "Error with chat loads"))
Не в этом реквесте, но тоже было бы найс в константы убрать стандартное сообщение ошибки

2023-05-04 20:38 UTC, Ret14 commented on app/src/main/java/com/example/roomer/data/remote/ChatClientWebSocket.kt
В этом файле надо убрать логгирование

2023-05-04 20:43 UTC, Ret14 requested changes
Замени хардкод на ресурсы и константы и защити либо измени логику, которая вызвала вопросы

2023-05-05 07:53 UTC, Dariaaa commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreen.kt
> +@Composable
а зачем тут Composable?

2023-05-05 07:54 UTC, Dariaaa commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreenViewModel.kt
> +            val response = roomerRepository.getMessages(chatId = chatId)
слишком много логики в этом месте, лучше вынести

2023-05-05 07:56 UTC, Dariaaa commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/chat_screen/ChatScreenViewModel.kt
> +        viewModelScope.launch {
viewModelScope.launch(Dispatchers.IO)

2023-05-06 10:56 UTC, Ret14 approved these changes
Круто!

2023-05-07 11:54 UTC, Ret14 approved these changes
Well done!

2023-05-07 11:55 UTC, merged