Feature home page
MoonLoone/roomer pull request #153
Opened 2023-05-08 11:31 UTC by MoonLoone

Главная страница готова. 
Сделал добавление в локальную базу истории через интерфейс.
В качестве критериев для рекомендаций (берем из инфы о текущем юзере):
пользователи - интересы, страна, sleepTime
комнаты - страна

2023-05-08 11:46 UTC, MoonLoone commented on app/build.gradle
> +
Это возможно ограничит ресурсы, потребляемые при сборке)

2023-05-10 06:32 UTC, Dariaaa approved these changes

2023-05-10 12:30 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/navbar_screens/home_screen/HomeScreenViewModel.kt
> +            _state.update { current ->
Инит перегружен, пожалуйста разбей логику по функциям

2023-05-10 12:34 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/navbar_screens/home_screen/HomeScreen.kt
> +    if (state.unauthorized) {
Неавторизованный юзер никогда не попадет на главную

2023-05-10 12:48 UTC, Ret14 commented on app/src/main/java/com/example/roomer/data/shared/AddToHistory.kt
> +            roomerRepositoryInterface.addMateToLocalHistory(user)
Mate поменяй на Roommate или User везде

2023-05-10 13:50 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/navbar_screens/home_screen/HomeScreen.kt
Класс)

2023-05-10 13:54 UTC, Ret14 commented on app/src/main/java/com/example/roomer/data/repository/model/RecommendedRoomModel.kt
Зачем сделал еще один класс и не использовал LocalRoom или Room?

2023-05-10 13:57 UTC, Ret14 requested changes
Нужно разделить логику во вью модели HomeScreen, объяснить почему использовал неподходящую сущность, для чего добавил новые классы в model, а не использовал существующие. И желательно названия поменять на более подходящие

2023-05-10 13:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/data/repository/model/RecommendedRoomModel.kt
Эти сущности используются только в запросе. Из частей собираются и парсятся для запроса на бэк. Удобно, что не нужно везде тащить кучу переменных и что автоматом проставлен null где нужно

2023-05-10 16:22 UTC, merged