Feature room details
MoonLoone/roomer pull request #165
Opened 2023-05-13 16:50 UTC by Iascatt

2023-05-14 10:26 UTC, Ret14 commented on app/src/main/java/com/example/roomer/utils/RoomTypeSerializer.kt
Такой файл уже есть в utils/navigation, используй его)

2023-05-14 10:27 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/ui_components/ui_components.kt
> +// import com.example.roomer.presentation.screens.destinations.RoomDetailsScreenDestination
Убери комментарий

2023-05-14 10:36 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/room_details/RoomDetailsScreen.kt
Экран перегружен, нужно разбить логику

2023-05-14 10:38 UTC, Ret14 commented on app/src/main/java/com/example/roomer/data/shared/housing_like/HousingLike.kt
> +        housing.isLiked = true
Убрать isLiked

2023-05-14 10:38 UTC, Ret14 commented on app/src/main/java/com/example/roomer/data/shared/housing_like/HousingLike.kt
> +        housing.isLiked = false
Убрать isLiked

2023-05-22 14:57 UTC, MoonLoone requested changes

2023-05-22 14:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/room_details/RoomDetailsScreen.kt
> +                text = room.title,
Обрежь строку (StringUtils.trim ...)

2023-05-22 14:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/room_details/RoomDetailsScreen.kt
> +            text = location,
Тоже обрезай

2023-05-22 14:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/room_details/RoomDetailsScreen.kt
> +            text = (name),
Нещадно режем)

2023-05-22 14:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/room_details/RoomDetailsScreen.kt
> +            fontSize = 20.sp
Возьми из ресурсов

2023-05-25 08:46 UTC, MoonLoone approved these changes

2023-05-25 08:47 UTC, merged