Fix fav follow
MoonLoone/roomer pull request #179
Opened 2023-05-22 12:34 UTC by MoonLoone

Изменил логику подписок.
Не починил favourites. Мы решили перенести логику добавления и удаления избранного в RoomDetails, а этого экрана еще нет... Пока что просто убрал картинку сердца с карточки.

2023-05-22 19:23 UTC, Ret14 requested changes
Круто! Но есть несколько вещей, что вызвали вопросы

2023-05-22 19:23 UTC, Ret14 commented on app/src/main/java/com/example/roomer/domain/usecase/profile_nested_screens/FollowScreenUseCase.kt
Классно сделал с наследованием от FollowUseCase)

2023-05-22 19:23 UTC, Ret14 commented on app/src/main/java/com/example/roomer/domain/usecase/shared/FollowUseCase.kt
Сценарий отсутствия интернета мы больше не обрабатываем?(

2023-05-22 19:23 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenState.kt
Во view model ты используешь update, в var нет никакого смысла и их все можно заменить на val

2023-05-22 19:23 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenViewModel.kt
> +            user.let {
Если теперь гарантированно not null приходит, то в let нет никакого смысла

2023-05-22 19:23 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenViewModel.kt
> +                    else -> _state.update { current ->
Сценарий без интернета мы больше не обрабатываем?(

2023-05-22 19:23 UTC, Ret14 commented on app/src/main/java/com/example/roomer/utils/Constants.kt
> +        const val FOLLOW_PROBLEM = "follow problem"
Информативно)

2023-05-23 05:48 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/domain/usecase/shared/FollowUseCase.kt
Fixed

2023-05-23 05:58 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenState.kt
Fix

2023-05-23 06:00 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenViewModel.kt
> +            user.let {
Тут нет гарантии, поэтому проверка необходима (мы из хэндлера берем юзера, там легко может null прилететь)

2023-05-23 06:02 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenViewModel.kt
> +                    else -> _state.update { current ->
Fixed

2023-05-23 06:45 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/utils/Constants.kt
> +        const val FOLLOW_PROBLEM = "follow problem"
Fixed

2023-05-23 07:23 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenViewModel.kt
> +            user.let {
Тогда используй user?.let, без ? в лямбде окажется null

2023-05-23 07:25 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenViewModel.kt
> +            user.let {
Как это отработает? Сейчас если null, то он не будет даже пытаться добавить запись в бд. Здесь это обрабатывается очень просто

2023-05-23 07:27 UTC, Ret14 requested changes
Исправь логику let

2023-05-23 07:29 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenViewModel.kt
> +            user.let {
Сейчас если null, то операция все равно запустится. Если добавить ?, то блок когда внутри let не будет выполняться при null

2023-05-23 07:31 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/shared_screens/user_details_screen/UserDetailsScreenViewModel.kt
> +            user.let {
Понял. Не знаю, зачем вопрос убирал)

2023-05-23 07:50 UTC, Ret14 approved these changes
Круто

2023-05-23 07:50 UTC, merged