Feature search
MoonLoone/roomer pull request #82
Opened 2023-03-28 13:35 UTC by Iascatt

2023-03-29 10:19 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/data/remote/RoomerApi.kt
> +       @Query("month_price_from") monthPriceFrom: String?,
Зачем nullable?

2023-03-29 10:26 UTC, MoonLoone requested changes
На мой взгляд нужны фиксы

2023-03-29 10:26 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/data/remote/RoomerApi.kt
> +       @Query("month_price_from") monthPriceFrom: String?,
Зачем nullable?

2023-03-29 10:26 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/data/repository/SearchRepository.kt
> +}
Нужен ли нам отдельный репозиторий под поиск?

2023-03-29 10:26 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/di/AppModule.kt
> +import com.example.roomer.data.repository.*
Hard import

2023-03-29 10:26 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/domain/model/entities/Room.kt
> +    val host: Int = 0,
Почему храним айдишник, а не пользователя?

2023-03-29 10:26 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomResultsViewModel.kt
> +        housingType: String?,
Зачем nullable?

2023-03-29 10:26 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateScreen.kt
> +                    Pair("A", "Any")
Этот хардкод нужно будет поменять

2023-03-29 10:26 UTC, MoonLoone commented on gradle.properties
> +android.nonTransitiveRClass=true
Нужен ли нам этот файлик?

2023-03-29 15:50 UTC, MoonLoone requested changes

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/domain/model/entities/Room.kt
> +    val host: Int = 0,
Понял)

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomResults.kt
> +import androidx.compose.foundation.layout.*
Wild import

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomResultsViewModel.kt
> +        housingType: String?,
Тут вероятно можно использовать не nullable.

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomScreen.kt
> +import androidx.compose.foundation.layout.*
Wildcard import

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateResultViewModel.kt
> +        cleanHabits: String?,
Возможно тут стоит убрать nullable

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateScreen.kt
> +import androidx.compose.foundation.layout.*
Wildcard import

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateScreen.kt
> +import com.example.roomer.presentation.ui_components.*
Wildcard import

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateScreen.kt
> +                                Toast.makeText(context, "Not numeric value", Toast.LENGTH_SHORT)
Hardcode

2023-03-29 15:50 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateScreen.kt
> +                                Toast.makeText(context, "Not numeric value", Toast.LENGTH_SHORT)
Hardcode

2023-03-30 10:53 UTC, Dariaaa commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateScreen.kt
> +        modifier = Modifier.padding(start = 40.dp, end = 40.dp, top = 16.dp, bottom = 40.dp),
значения dimens лучше пока вытащить в переменные, а потом добавить их в тему

2023-04-22 16:28 UTC, Ret14 commented on app/src/main/java/com/example/roomer/domain/model/entities/Room.kt
> +    val host: User = User(),
Для чего здесь убран null и проставляется дефолтное значение? Без этого что-то ломалось?

2023-04-22 16:29 UTC, Ret14 commented on app/src/main/java/com/example/roomer/domain/usecase/search/SearchUseCase.kt
> +                coroutineScope {
Тут можно убрать coroutineScope, emit будет отрабатывать и без него

2023-04-22 16:32 UTC, Ret14 commented on app/src/main/res/values/dimens.xml
> +    <!--Filters screens-->
Зачет, что коммент поставила, отделяющий твои dimens)

2023-04-22 16:35 UTC, Ret14 commented on app/src/main/java/com/example/roomer/utils/Constants.kt
Скорее хочу эти константы в develop)

2023-04-22 16:45 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateResults.kt
> +    _sex: String?,
Как-то очень много параметров в функции. Кажется, что лучше  дата класс с ними создать, проставлять и передавать. Или вью модель для двух экранов с этими параметрами внутри

2023-04-22 16:49 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomScreen.kt
> +                    color = Color.Black,
Этот цвет есть в ресурсах, лучше оттуда вызывать

2023-04-22 16:51 UTC, Ret14 commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomResultsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO + coroutineExceptionHandler) { block() }
Для чего этот код?

2023-04-22 16:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomResults.kt
> +    Log.d("catching", rooms.toString())
Логирование нужно убрать

2023-04-22 16:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomScreen.kt
> +    val context = LocalContext.current
Лучше не хранить контекст в переменной

2023-04-22 16:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomScreen.kt
>          ),
Зачем свой Scaffold?

2023-04-22 16:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoommateScreen.kt
>          ),
Опять Scaffold

2023-04-22 16:57 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/utils/Constants.kt
> +        val roomsCountOptions = listOf(R.string.any, R.string._1, R.string._2, R.string._3)
Нам нужно выносить в ресурсы цифры?

2023-04-22 16:57 UTC, MoonLoone commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
Не посыпимся от нового gradle?

2023-04-22 16:59 UTC, MoonLoone approved these changes
Все хорошо

2023-04-22 17:04 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomResultsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO + coroutineExceptionHandler) { block() }
Просто для удобства) Еще прикручен handler ошибок корутин

2023-04-22 17:57 UTC, Iascatt commented on app/src/main/java/com/example/roomer/domain/model/entities/Room.kt
> +    val host: User = User(),
Изначально поле host было Int, я поменяла на User таким способом. Наверное, действительно лучше сделать nullable

2023-04-22 18:00 UTC, Iascatt commented on app/src/main/java/com/example/roomer/presentation/screens/search_screens/SearchRoomResultsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO + coroutineExceptionHandler) { block() }
Пыталась найти ошибку, нашла такое решение. Оказалось, проблема в другом месте, ExceptionHandler остался.  Оставила, пока не мешал и мог пригодится в дальнейшем. Можно убрать.

2023-04-25 09:55 UTC, MoonLoone approved these changes
Все ок. В следующем релизе добавим пагинацию и сделаем классы для проброса данных между экранами

2023-04-25 09:55 UTC, merged