Feature localization
MoonLoone/roomer pull request #96
Opened 2023-04-16 10:51 UTC by Andrey-Karanik

Removed all hardcoded strings and added russian localization!

2023-04-16 15:42 UTC, MoonLoone commented
Все окей, но нужно, чтобы прошли все проверки ktlint. Много wildcard import

2023-04-16 15:43 UTC, MoonLoone requested changes

2023-04-16 15:43 UTC, MoonLoone commented on app/src/main/java/com/example/roomer/presentation/screens/navbar_screens/MessengerScreen.kt
> +import androidx.compose.ui.res.*
Нужно убрать везде wildcard import (импорт с *)

2023-04-16 22:02 UTC, Andrey-Karanik commented on app/src/main/java/com/example/roomer/presentation/screens/navbar_screens/MessengerScreen.kt
> +import androidx.compose.ui.res.*
хорошо

2023-04-17 06:49 UTC, MoonLoone approved these changes
Все классно)

2023-04-17 06:50 UTC, merged